name: Build and Test UAC

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build UltimateAnticheat.sln (LibRelease x64)
      run: msbuild UltimateAnticheat.sln /p:Configuration=LibRelease /p:Platform=x64

    - name: Build UltimateAnticheat.sln (Release x64)
      run: msbuild UltimateAnticheat.sln /p:Configuration=Release /p:Platform=x64

    - name: Run UACLibTest.exe and capture output
      shell: pwsh
      run: |
        Write-Host "Starting test..."
        $process = Start-Process -FilePath .\x64\Release\UACLibTest.exe -NoNewWindow -RedirectStandardOutput output.log -RedirectStandardError error.log -PassThru
        if (-not $process.WaitForExit(30)) {
          Write-Error "Test timed out after 30s"
          Stop-Process -Id $process.Id -Force
          exit 1
        }
        Write-Host "Exit code: $($process.ExitCode)"
        exit $process.ExitCode
        
    - name: Upload UACTest output
      uses: actions/upload-artifact@v4
      with:
        name: UACLibTestLog
        path: output.log
